package game.actions;

import input.InputType;

final ACTION_INPUT_TYPES: Map<Action, InputType> = [
	PAUSE => PRESS, MENU_LEFT => REPEAT, MENU_RIGHT => REPEAT, MENU_DOWN => REPEAT, MENU_UP => REPEAT, BACK => PRESS, CONFIRM => PRESS, SHIFT_LEFT => HOLD,
	SHIFT_RIGHT => HOLD, SOFT_DROP => HOLD, HARD_DROP => PRESS, ROTATE_LEFT => PRESS, ROTATE_RIGHT => PRESS, TOGGLE_EDIT_MODE => PRESS, EDIT_LEFT => REPEAT,
	EDIT_RIGHT => REPEAT, EDIT_DOWN => REPEAT, EDIT_UP => REPEAT, EDIT_SET => PRESS, EDIT_CLEAR => PRESS, PREVIOUS_STEP => REPEAT, NEXT_STEP => REPEAT,
	PREVIOUS_COLOR => REPEAT, NEXT_COLOR => REPEAT, PREVIOUS_GROUP => REPEAT, NEXT_GROUP => REPEAT, TOGGLE_MARKERS => PRESS
];
